### ISSUE TITLE
table view delegates(did select) stop working after protecting view

### ISSUE THREAD

**Issue by mayurb9494** [JayantBadlani/ScreenShield#10]
min deployment iOS version 13
target version iOS 17.4
tableview didselect not working 
![Screenshot 2024-04-18 at 9 44 45 AM](https://github.com/JayantBadlani/ScreenShield/assets/48545554/66635e47-1dca-417a-b8e9-be7f5c68d74c)
video: 

https://github.com/JayantBadlani/ScreenShield/assets/48545554/beed4a48-12a5-45c7-aaef-b8955aed5f2a

**Comment by JayantBadlani** [comment]
Hi @mayurb9494, You can try adding "ScreenShield" protection to your view after the UI finishes loading. Implementing this protection in the **viewDidAppear** method can effectively mitigate problems. I hope this resolves your issue.

I also suggest checking out the [README](https://github.com/JayantBadlani/ScreenShield/blob/main/README.md) file for more detailed instructions and information.

**Comment by mayurb9494** [comment]
tried but not working!
here is project: 
[Demo.zip](https://github.com/JayantBadlani/ScreenShield/files/15020387/Demo.zip)


check ScreenShieldViewController

**Comment by JayantBadlani** [comment]
@mayurb9494 You can use this workaround solution to achieve the desired result. 
here is the working project:
[DemoTableClickWorking.zip](https://github.com/JayantBadlani/ScreenShield/files/15022013/DemoTableClickWorking.zip)


Please leave a star ⭐️ on my repo if I and my repo are able to help you. Thank you!
