### ISSUE TITLE
'View' is only available in iOS 13.0 or newer ERROR

### ISSUE THREAD

**Issue by Simimi-dot** [JayantBadlani/ScreenShield#5]
I just installed it through SPM, and it’s not letting the project work. The following errors appear (attached screenshot). Minimum version of the iOS 16 project
<img width="1980" alt="Снимок экрана 2024-02-17 в 20 04 13" src="https://github.com/JayantBadlani/ScreenShield/assets/72037407/8e2675e2-f533-4bae-bf91-2b8e2e593026">

**Comment by JayantBadlani** [comment]
@Simimi-dot Thank you for letting me know. The above issue has been fixed and pushed to version 1.2.1.
