### ISSUE TITLE
Alert message Not hidden in SwiftUI

### ISSUE THREAD

**Issue by Prathap-Aosta** [JayantBadlani/ScreenShield#9]
1. After the alert popup was displayed, I took a screenshot, but the alert message was not hidden.
![Simulator Screenshot - iPhone 15 Pro Max - 2024-03-27 at 13 15 14](https://github.com/JayantBadlani/ScreenShield/assets/112875721/4d7b4d4a-ad4f-4ce0-b5dd-5740f0c4c66f)

2. Native iOS Menu popup was displayed, I took a screenshot, but the menu was not hidden.
![Simulator Screenshot - iPhone 15 Pro Max - 2024-03-27 at 16 24 19](https://github.com/JayantBadlani/ScreenShield/assets/112875721/15471f95-4d84-4825-adf1-f0507ccad22d)

import SwiftUI
import ScreenShield

struct ContentView: View {
    @State private var presentAlert = false
    @State private var menutext = ""
    @State private var arrayMenuVal = ["Apple", "Orange", "Mango", "Grape"]
    
    var body: some View {
        ZStack{
            Color.red.ignoresSafeArea()

        VStack {
            Text("Sensative Information")
                .padding(.bottom, 50)
                .font(.title)
            Image("sensitive1")
                .resizable()
                .frame(maxWidth: .infinity)
                .aspectRatio(contentMode: .fit)
            
            Menu {
                ForEach(arrayMenuVal, id: \.self){ val in
                    Button("\(val)") {
                        menutext = val
                    }
                }
            } label: {
                TextField(text: $menutext, label: {
                    Text("Menu")
                        .foregroundColor(.white)
                        .font(.footnote)
                })
            }
            .padding(.top, 20)

            Button("Alert popup") {
                presentAlert = true
            }
            .font(.footnote)
            .foregroundColor(.white)
            .buttonBorderShape(ButtonBorderShape.capsule)
            .padding(.top, 30)
        }
        .alert(isPresented: $presentAlert) {
            Alert(title: Text("Test for screenshot"))
        }
    }
        .padding()
        .protectScreenshot()
        .onAppear {
            ScreenShield.shared.protectFromScreenRecording()
        }
    }
}

**Comment by JayantBadlani** [comment]
@Prathap-Aosta, It's not possible to hide the native OS alerts and menu that appear on a separate layer of the view. If you want to hide the alerts, create your custom alerts.

**Comment by Prathap-Aosta** [comment]
@JayantBadlani  Okay, Thanks
